
version: "3.8"

services:
  smilecdr:
    container_name: smilecdr
    image: kidsfirstdrc/smilecdr:2023.05.R02
    env_file:
      - .env
    ports:
      - "8000:8000"
      - "9000:9000"
      - "9100:9100"
      - "8001:8001"
      - "9200:9200"
      - "9201:9201"
    volumes:
      # Server with Postgres DB
      - ./smilecdr/settings/server-postgres.properties:/home/smile/smilecdr/classes/cdr-config-Master.properties
      # Server with embedded H2 DB
      # - ./smilecdr/settings/server-quickstart.properties:/home/smile/smilecdr/classes/cdr-config-Master.properties
      - ./smilecdr/settings/jvm.sh:/home/smile/smilecdr/bin/setenv
      - ./smilecdr/settings/system-users.json:/home/smile/smilecdr/classes/config_seeding/users.json
      - ./smilecdr/settings/oidc-servers.json:/home/smile/smilecdr/classes/config_seeding/oidc-servers.json
      - ./smilecdr/settings/auth.js:/home/smile/smilecdr/classes/config_seeding/auth.js
    restart: "unless-stopped"
    depends_on:
      - smilecdr_postgres
      - keycloak

  smilecdr_postgres:
    container_name: smilecdr_postgres
    image: postgres:11.4-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: ${POSTGRES_ADMIN_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
    volumes:
      - ./smilecdr/postgres/init_postgresdb.sh:/docker-entrypoint-initdb.d/init_postgresdb.sh
      - smilecdr_db:/var/lib/postgresql/data
    restart: unless-stopped

  keycloak:
    container_name: 'keycloak'
    image: quay.io/keycloak/keycloak:21.0.2
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    ports:
      - "8080:8080"
    command: start-dev --hostname-strict-backchannel=true --import-realm
    volumes:
      - ./keycloak/settings:/opt/keycloak/data/import

  web:
    container_name: web_app
    build:
      context: web_app
    depends_on:
      - keycloak
    env_file:
      .env
    ports:
      - '8081:8081'
    volumes:
      - ./web_app/:/home/app
      - /home/app/venv
volumes:
  smilecdr_db:
