# Smile CDR stack that uses in-memory database
version: "3.7"
services:
  smilecdr:
    container_name: smilecdr
    image: smilecdr
    ports:
      - "8000:8000"
      - "9000:9000"
      - "9100:9100"
      - "8001:8001"
      - "9200:9200"
      - "9201:9201"
    volumes:
      - db:/home/smile/smilecdr/database
      - log:/home/smile/smilecdr/log
      - mq:/home/smile/smilecdr/activemq-data
    restart: unless-stopped
volumes:
  db:
  mq:
  log:
