version: "3.7"
services:
  smilecdr:
    container_name: smilecdr
    image: smilecdr:2020.02.R01
    depends_on:
      - postgresdb
    volumes:
      - ./classes/cdr-config-Master.properties:/home/smile/smilecdr/classes/cdr-config-Master.properties
      - ./classes/logback.xml:/home/smile/smilecdr/classes/logback.xml
      - ./bin/setenv:/home/smile/smilecdr/bin/setenv
      - smilecdr_log:/home/smile/smilecdr/log
      - smilecdr_mq:/home/smile/smilecdr/activemq-data
      - smilecdr_lucene:/home/smile/smilecdr/database/lucene_fhir_persistence
    restart: unless-stopped
  postgresdb:
    container_name: postgres_cdr
    build:
      context: ./postgres
    image: postgres_cdr
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_SUPER_USER_ID}
      - POSTGRES_PASSWORD=${DB_SUPER_USER_PASSWORD}
      - CDR_DB_NAME=${DB_CDR_NAME}
      - CDR_USER=${DB_CDR_USERID}
      - CDR_PASSWORD=${DB_CDR_PASSWORD}
    volumes:
      - smilecdr_db:/var/lib/postgresql/data
    restart: unless-stopped
  nginx:
    depends_on:
      - smilecdr
    container_name: nginx
    build:
      context: ./nginx
    expose:
      - 80
      - 443
      - 8000
      - 8001
      - 9000
      - 9100
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
      - "8001:8001"
      - "9000:9000"
      - "9100:9100"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./nginx/ssl.conf:/etc/nginx/ssl.conf
volumes:
  smilecdr_db:
  smilecdr_mq:
  smilecdr_log:
  smilecdr_lucene:
