# Use base Smile CDR image as parent image
FROM smilecdr

# Set working directory
WORKDIR /home/smile/smilecdr

# Copy the customized properties file from the context folder to the WORKDIR in the container.
COPY ./classes/cdr-config-Master.properties ./classes/cdr-config-Master.properties
